# Generated by Django 5.2.15 on 2026-06-21 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shorturl',
            old_name='orginal_url',
            new_name='original_url',
        ),
    ]
